### ISSUE TITLE
Errors at runtime

### ISSUE THREAD

**Issue by ErikBrewster** [mikepb/xforgot#1]
I am trying out Xforgot and ran into these problems:
1. const is not allowed when using 'use strict'. I can use --harmony on my server, but it sure would be nice to not have to have the server cater to one library.
2. The sample code on the front page didn't work for me. I get aan error 
   /home/myuser/myproject/node_modules/xforgot/xforgot.js:189
   options = Object.create(options);
                    ^
   TypeError: Object prototype may only be an Object or null: J9NJGAy1j55DeiQ2WQWTFUKvBwTJa4eSZfwdRJQbGeZR

If I change the usage from 
"if (xforgot.verify(token)) {..."
to 
"if (xforgot.verify({token:token})) {..."

I can avoid the error, but then I run into this:
_stream_writable.js:269
  var len = state.objectMode ? 1 : chunk.length;
                                        ^
TypeError: Cannot read property 'length' of undefined
    at writeOrBuffer (_stream_writable.js:269:41)
    at Hmac.Writable.write (_stream_writable.js:217:11)
    at XForgot.digestSecret (/home/myuser/myproject/node_modules/xforgot/xforgot.js:107:8)
    at XForgot.verify (/home/myuser/myproject/node_modules/xforgot/xforgot.js:194:39)

I'm using node 0.12.7 and xforgot 0.0.2. Any ideas?

My code:
...
var xforgot = require('xforgot');
...
var token = xforgot({secret: "xyzzy", salt: "foobar"});

```
    // Send token to user via URL...

    if (xforgot.verify({token:token})) {
      // Reset the user's password...
      var test = 1;
    }
```

When I step through the code, the token seems to be generated plausibly, with no errors. I only get the errors on the verify call.

**Comment by mikepb** [comment]
How embarrassing!

Yes, the API is `xforgot.verify({ token: token, secret: "xyzzy", salt: "foobar" })`.

Sorry for using `const`; I've been using iojs for a while now and forgot that nodejs still exists! Thankfully, future nodejs releases will be based on iojs and issues like these will soon be a thing of the past :smile: 

I've published `v0.0.3` to npm to fix the issues you found, including a clarification of when to use the `secret` and `salt` options.

Let me know if that fixes it for you.

**Comment by ErikBrewster** [comment]
Seems to work. Thanks for the quick fix!

**Comment by mikepb** [comment]
Closing as resolved.
